### ISSUE TITLE
Demo site is down

### ISSUE THREAD

**Issue by stevemoser** [rriemann/middleman-blog-template-duocolor#2]

**Comment by rriemann** [comment]
I just checked the link to the demo site that is given in the github repo description and mentioned in the readme: http://rriemann.github.io/middleman-blog-template-duocolor/

It works perfectly for me. I will close this issue. Please re-open if it still doesn’t work and provide more details.

**Comment by stevemoser** [comment]
Sorry this is the link I was speaking of that is linked from the page:
http://rriemann.github.io/demo/

**Comment by rriemann** [comment]
The links are fixed. I also updated some dependencies.

The changes are in master. As practically nothing changed apart from some slashes in the readme, I won't release a new version now.

**Comment by stevemoser** [comment]
:+1:
